// AnnaChain — the ATECC608B secure element: ECDSA P-256, key inside the chip.
//
// ╔══════════════════════════════════════════════════════════════════════════╗
// ║ UNPROVEN. This driver compiles. It has never talked to an ATECC608B:     ║
// ║ none has arrived. Treat every line as a hypothesis until docs/HIL.md     ║
// ║ step 4 has been run on a real part and its output recorded.              ║
// ╚══════════════════════════════════════════════════════════════════════════╝
//
// Which key it uses. The part on the buy list is the ATECC608B-TNGTLS
// (Trust&GO). Per its data sheet (Microchip DS40002250B, §2.1 and §2.2.1.1):
//   * its default 7-bit I2C address is 0x35, not the 0x60 of a blank ATECC608;
//   * its Configuration zone is locked at the factory and cannot be changed —
//     "already locked" is how it is supposed to arrive;
//   * slot 0 holds a permanent P-256 private key, randomly generated by the
//     chip's own TRNG, which "can never be read", enabled for ECDSA Sign.
// So the key is generated on-chip and is never readable, which is the property
// the HMAC stand-in cannot give. This driver signs with slot 0 and reads its
// public key with GenKey in public-key mode; it never writes to the chip.
//
// A blank ATECC608 (address 0x60, unlocked) needs its configuration written
// and locked first, which is irreversible. This driver refuses to do that and
// reports the part as unprovisioned; see docs/BRINGUP.md.
//
// It implements IEcdsaSigner, not ISigner: a 64-byte signature does not fit the
// 32-byte field in today's record. See ac_hal.h.
#pragma once
#ifdef ARDUINO
#include <Arduino.h>
#include <Wire.h>
#include "ac_hal.h"

namespace ac {

class AteccSigner : public IEcdsaSigner {
 public:
  static const uint8_t kAddrTrustGo = 0x35;   // ATECC608B-TNGTLS [DS40002250B §2.1]
  static const uint8_t kAddrBlank   = 0x60;   // a standard ATECC608

  explicit AteccSigner(TwoWire& wire = Wire, int slot = 0) : wire_(wire), slot_(slot) {}

  // Tries 0x35, then 0x60. True only for a part whose config and data zones
  // are both locked: an unlocked part cannot be trusted to hold a key.
  bool begin() override;
  bool publicKey(uint8_t pub[64]) override;
  bool sign(const uint8_t digest[32], uint8_t sig[64]) override;

  // For the smoke test and the bring-up log.
  bool present() const { return addr_ != 0; }
  uint8_t address() const { return addr_; }
  bool locked() const { return locked_; }
  String serialNumber();                 // 18 hex characters, empty on failure
  const char* lastError() const { return err_; }

 private:
  TwoWire& wire_;
  int slot_;
  uint8_t addr_ = 0;
  bool locked_ = false;
  const char* err_ = "not started";
};

// Check an ECDSA P-256 signature in software (mbedTLS), independently of the
// chip. The server will need exactly this check for a v2 record; running it on
// the board proves the chip's output is a standard signature, not merely one
// the chip itself agrees with.
bool ecdsaVerifySoftware(const uint8_t pub[64], const uint8_t digest[32],
                         const uint8_t sig[64]);

}  // namespace ac
#endif  // ARDUINO
